import Head from "next/head";

import { Col } from "@/shared/ui/col";
import { Container } from "@/shared/ui/container";
import { Row } from "@/shared/ui/row";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <Container>
        <Row>
          <Col lg={4} md={2} sm={1}>
            TEST
          </Col>
        </Row>
      </Container>
    </>
  );
}
